Websocket listeners are now kept after browser or node websockets reconnect
0cfg/0cfg-rpc pull request #2
Opened 2021-03-19 12:58 UTC by jonas-zipprick

# Def. of Done
- [ ] Changes described in changelog.md 📝 
- [x] Automatic tests written 🧪
- [ ] Manually tested 🧪
- [x] Good code style
- [x] Necessary migrate instructions added to migrate.md 🚀
- [x] No known issues

2021-03-19 14:57 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +    private readonly eventListeners:
All event listeners should be reapplied on reconnect. This map should not be there/necessary and could create bugs with rpc if a straming service which was already closed is restarted by mistake.

2021-03-19 14:58 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +    /**
None of these do, add just one comment to the class that all ws event handlers need to be reaplied on reconnection.
Also remove the getter/setter comments.

2021-03-19 14:59 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +        this.eventListeners[type].push(listener);
please remove, as described above.

2021-03-19 14:59 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +    public removeEventListener<K extends keyof WebSocketEventMap>(
can just forward to the current socket.

2021-03-19 15:01 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +            });
remove, event listeners should be reapplied by clients on reconnection.

2021-03-19 15:02 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +                () => resolve(errStatus('Connection timeout.')),
need to close the socket on a connection timeout

2021-03-19 15:03 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +                resolve(errStatus('Host unreachable.'));
log the event itself

2021-03-19 15:03 UTC, eliasgroll commented on packages/stubs/node/src/ts/messaging/ReconnectingWebSocket.ts
> +    private readonly eventListeners:
same as for the client

2021-03-19 15:04 UTC, eliasgroll commented on packages/stubs/node/src/ts/messaging/__tests__/ReconnectingWebSocket.test.ts
> +    expect(closedMock.mock.calls.length).toBeGreaterThan(100);
Why is this greater 100?

2021-03-19 15:05 UTC, eliasgroll requested changes
All clients should handle the reconnection themselves, in terms of restarting the services.  Backends can not detect that this is the same browser tab.

2021-03-19 17:58 UTC, jonas-zipprick commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +    private readonly eventListeners:
I can't think of one case where you don't want to reapply the listener on reconnect.
Why should it not be the default behavior?
Can you give an example of one such potential bug?

2021-03-19 18:00 UTC, jonas-zipprick commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +    private readonly eventListeners:
Another point: Libraries that treat the reconnecting websocket as a normal websocket over the Websocket interface don't know that they have to re-add listeners on reconnect (onReconnect is not a part of the browser websocket interface). 

There is no point to use a reconnecting websocket over a normal websocket with those libraries because of that if we don't reapply automatically.

2021-03-19 18:05 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +    private readonly eventListeners:
The server does notice that the connection is lost and ends the stream, there will never be another message from the server on the same stream.

2021-03-19 19:01 UTC, eliasgroll commented
As discussed offline, we are going to:

1. Keep the event listeners on the ReconnectingWebSocket between reconnections
2. Remove listeners attached by Services from the ReconnectingWebSocket on a connection loss
3. Throw an error if a stream stub is reused after a connection loss (we want to force creating a new stream)
4. Add comments about this intended behaviour

2021-03-19 19:53 UTC, jonas-zipprick commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +                resolve(errStatus('Host unreachable.'));
The event itself contains no information about the cause of the error.

2021-03-20 17:07 UTC, jonas-zipprick commented on packages/stubs/node/src/ts/messaging/__tests__/ReconnectingWebSocket.test.ts
> +    expect(closedMock.mock.calls.length).toBeGreaterThan(100);
I think there are simply a lot of retries until the server is finally reachable again

2021-03-20 17:11 UTC, jonas-zipprick commented on packages/stubs/node/src/ts/messaging/__tests__/ReconnectingWebSocket.test.ts
> +    expect(closedMock.mock.calls.length).toBeGreaterThan(100);
Ah, there was a problem with test setup. It's now 6

2021-03-20 17:18 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
> +        this.messageListener = (data) => this.parseAndForwardServerMessage(data);
message listener should live only within the constructor context.

2021-03-20 17:18 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
> +            throw new Error('Bidi stream already completed.');
`Can not send messages on a completed stream (requestId: ${requestId}).`

2021-03-20 17:18 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
> +            this.socket.removeEventListener('event', this.messageListener);
Listening on the "message" event above, should it be the same?

2021-03-20 17:18 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketServerStreamStub.ts
>      public constructor(socket: CommonReconnectingWebSocket, requestIdSequential: Sequential, method: string) {
Could ServerStream and BidiStream Stub extend the same base class?

2021-03-20 17:18 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketServerStreamStub.ts
> +            throw new Error('Server stream already completed.');
Same like with the bidi stream error message.

2021-03-20 17:18 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketServerStreamStub.ts
>      public complete(end: Reply): void {
Should we remove the listeners here as well? Or do we wait for a server complete message (not sure atm).

2021-03-20 17:18 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
> +        send<SerializedReply>(this.socket, {
Should we remove the listeners here as well? Or wait for the complete message by the server?

2021-03-20 17:18 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketServerStreamStub.ts
> +        this.messageListener = data => this.parseAndForwardServerMessage(data);
Same as with the message listener in the bidi stream.

2021-03-20 17:18 UTC, eliasgroll commented on packages/stubs/common/src/ts/messaging/CommonReconnectingWebSocket.ts
> +    public abstract removeEventListener(type: string, listener: (this: any, ev: any) => any): void;
Add a comment.

2021-03-20 17:18 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
>  export class WebSocketBidiStreamStub<ClientMessageT, ServerMessageT>
Can we add a test for these listeners via the serverside socket?

2021-03-20 17:19 UTC, eliasgroll commented
Nice!

2021-03-20 17:23 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +                resolve(errStatus('Host unreachable.'));
I see, we should maybe just listen for the close event, where we have a code (which can be an error code as above).
See here: https://stackoverflow.com/a/18804298. As far as I understood, the close event will be called with every error event after the socket was closed. Might event be cleaner to wait for the close (See https://stackoverflow.com/a/18804298).

2021-03-20 17:44 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
> +        this.messageListener = (data) => this.parseAndForwardServerMessage(data);
Wouldn't compile. It's used in `parseAndForwardServerMessage`

2021-03-20 17:47 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
> +            this.socket.removeEventListener('event', this.messageListener);
Yep, updated

2021-03-20 17:49 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketServerStreamStub.ts
>      public complete(end: Reply): void {
With this PR it is removed after the stream is completed.

2021-03-20 18:00 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketServerStreamStub.ts
>      public constructor(socket: CommonReconnectingWebSocket, requestIdSequential: Sequential, method: string) {
Jup. They have a lot in common.

2021-03-20 18:02 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
> +        send<SerializedReply>(this.socket, {
Where are we adding a listener in this line?

2021-03-20 18:02 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketServerStreamStub.ts
> +        this.messageListener = data => this.parseAndForwardServerMessage(data);
Wouldn't compile. It's used in parseAndForwardServerMessage

2021-03-20 18:02 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
>  export class WebSocketBidiStreamStub<ClientMessageT, ServerMessageT>
What are `these listeners` ?

2021-03-20 19:08 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketStreamStub.ts
> +export abstract class WebSocketStreamStub<ServerMessageT> {
I think server stream could even just exted the bidi stream.

2021-03-20 19:18 UTC, eliasgroll requested changes

2021-03-20 19:18 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketStreamStub.ts
> +export abstract class WebSocketStreamStub<ServerMessageT> {
Can you add comments?

2021-03-20 19:18 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketStreamStub.ts
> +    public constructor(socket: CommonReconnectingWebSocket, requestIdSequential: Sequential, method: string) {
Can be protected.

2021-03-20 19:18 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +                () => resolve(errStatus('Connection timeout.')),
Please close the socked.

2021-03-20 19:18 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +                () => resolve(errStatus('Connection timeout.')),
Connection timed out

2021-03-20 19:18 UTC, eliasgroll commented on packages/stubs/node/src/ts/messaging/ReconnectingWebSocket.ts
>          this.throwIfNotYetConnected();
Should we add this to the listener maps as well?

2021-03-20 19:18 UTC, eliasgroll commented on packages/stubs/node/src/ts/messaging/ReconnectingWebSocket.ts
> +    /**
Can we decide for one strategy, like all listeners survive reconnects?
Commetns should be changed as well

2021-03-21 08:47 UTC, jonas-zipprick commented on packages/stubs/node/src/ts/messaging/ReconnectingWebSocket.ts
>          this.throwIfNotYetConnected();
No, because this is a setter of a field. But we could read out the set listeners from the socket before deleting it and set it on the new socket in `connectToExternalService`.

But we never used those setters anyway.

2021-03-21 08:50 UTC, jonas-zipprick commented on packages/stubs/node/src/ts/messaging/ReconnectingWebSocket.ts
>          this.throwIfNotYetConnected();
I did that

2021-03-21 08:51 UTC, jonas-zipprick commented on packages/stubs/node/src/ts/messaging/ReconnectingWebSocket.ts
> +    /**
ok

2021-03-21 10:35 UTC, jonas-zipprick commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +                resolve(errStatus('Host unreachable.'));
Yeah, this is a seperate issue though I think. Because it is already in master.

2021-03-21 10:36 UTC, jonas-zipprick commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +                resolve(errStatus('Host unreachable.'));
https://github.com/0cfg/0cfg-rpc/issues/3

2021-03-21 10:42 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +     * Stays set even after reconnects.
Would rather add this to a this.oncloseListener.
Is the behavour, that old listeners get removed if this is set? If so lets use a field instead of a socket & exception if the socket was not connected.

2021-03-21 10:42 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketStreamStub.ts
>      protected readonly completeListeners: CompleteListener[] = [];
A socket can not be completed (only closed) please rename and use accordingly.

2021-03-21 10:42 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +            const onclose = this.socket ? this.socket.onclose : null;
lets use a field for this

2021-03-21 10:42 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
>  export class WebSocketBidiStreamStub<ClientMessageT, ServerMessageT>
i meant lets add a test for the subs

2021-03-21 10:42 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +                resolve(errStatus(`Host unreachable. ${JSON.stringify(ev)}.`));
Why do we do this here if we can just use close?
Is close not called if the socket was never connected? In this case lets only resolve if the socker was never connected, otherwise use the "close" event and provide a detailed error message.

2021-03-21 10:42 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketServerStreamStub.ts
> +        this.messageListener = data => this.parseAndForwardServerMessage(data);
Pass it to parseAndForwardServerMessage

2021-03-21 10:42 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
> +        send<SerializedReply>(this.socket, {
Currently we create the message listener in the constructor and only remove it when we receive a complete message form the server or when the socket disconnects. When we complete from the client side, we are currently not removing it directly but wait for the server message.

2021-03-21 10:46 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
> +            throw new Error('Bidi stream already completed.');
Please use the provided error message: Can not send messages on a completed stream (requestId: ${requestId}).

Write

2021-03-21 10:47 UTC, eliasgroll commented on packages/stubs/node/src/ts/messaging/ReconnectingWebSocket.ts
>          this.throwIfNotYetConnected();
Please use a field to set it before the socket is connected.

2021-03-21 10:48 UTC, jonas-zipprick commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +     * Stays set even after reconnects.
>> Is the behavour, that old listeners get removed if this is set?
Listeners previously set with this setter get overwritten (default setter behaviour)
Listeners added with `addEventListener` stay added.

If we create our own field `oncloseListener` we store the listener twice (once in our own field and once in `socket.onclose`).
This would be redundant data.

If the socket is not connected you still want to be able to add listeners. That's also the behaviour of the default websocket.
It should not throw an execption.

2021-03-21 10:51 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketStreamStub.ts
>      protected readonly completeListeners: CompleteListener[] = [];
The `completeListeners` field contains listeners added with `WebSocketStreamStub.onComplete` so i think this name is fitting.
I don't see the connection to sockets that you are drawing.

2021-03-21 10:53 UTC, jonas-zipprick commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +            const onclose = this.socket ? this.socket.onclose : null;
In the current PR state, listeners can already be added while the socket is not connected (at no point in time is `this.socket` undefined only "between" line 186 and 187 but there is no await there that would interrupt execution flow).

2021-03-21 10:54 UTC, jonas-zipprick commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +                resolve(errStatus(`Host unreachable. ${JSON.stringify(ev)}.`));
Don't know. This is coming from master, didn't change the master behaviour.

2021-03-21 10:58 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
>      public onCompleted(listener: CompleteListener): void {
should be protected and abstract or do something

2021-03-21 10:59 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketStreamStub.ts
> +    public complete(end: Reply): void {
Should we remove the message listener from the websocket here as well?

2021-03-21 11:00 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +     * Stays set even after reconnects.
Currently we throw an exception, then please use a field so we do not have to throw one.

2021-03-21 11:00 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketStreamStub.ts
>      protected readonly completeListeners: CompleteListener[] = [];
Sorry, my mistook this for the websocket,

2021-03-21 11:01 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
>      public onCompleted(listener: CompleteListener): void {
The code you reference is outdated. Can you please update your comment?

2021-03-21 11:01 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketServerStreamStub.ts
> +        this.complete(getOk());
Why would you complete right after starting?

2021-03-21 11:02 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +                resolve(errStatus(`Host unreachable. ${JSON.stringify(ev)}.`));
I sent you a link to stack overflow about the behaviour and how to fix this. 
You touched it so we should change it here.

2021-03-21 11:04 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> + * Only listeners added with {@link addEventListener} will still be receiving server messages after reconnects.
This comment should be reverted as we fix it.

2021-03-21 11:04 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketStreamStub.ts
> +    public complete(end: Reply): void {
Not sure. If we do that then we will also try to remove it later when the server response (in `parseAndForwardServerMessage`). The second time it will fail and propably throw an exception which we would have to catch.

If the server is unrechable the socket gets closed and we complete anyway

2021-03-21 11:06 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketServerStreamStub.ts
> +        this.complete(getOk());
Don't know. This is master behaviour.

2021-03-21 11:07 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketStreamStub.ts
> +        this.messageListener = (data) => this.parseAndForwardServerMessage(data);
Pass message listener to parseAndForwardServerMessage and remove it from the fields. Should only live in this context.

2021-03-21 11:08 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
>      public onCompleted(listener: CompleteListener): void {
Sure

2021-03-21 11:09 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketStreamStub.ts
> +    public complete(end: Reply): void {
Good point. Resolving this.

2021-03-21 11:10 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketStreamStub.ts
> +        this.messageListener = (data) => this.parseAndForwardServerMessage(data);
Ok

2021-03-21 11:11 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
> +            throw new Error('Bidi stream already completed.');
Code is outdated. Please update your comment or resolve.

2021-03-21 11:13 UTC, eliasgroll commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +            const onclose = this.socket ? this.socket.onclose : null;
Afaiu, the this.socket does not exist after the constructor was invoked. 
Also, a field is cleaner than using the old socket. Could always happen that someone adds new code in between 186 and 187.

2021-03-21 11:19 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketServerStreamStub.ts
> +        this.complete(getOk());
Master completes if there was already a requestId (if a running or completed stream is restarted).
In a previous comment we agreed that a stream should never be restarted but recreated by the stream factory.
The complete here can go away but we should throw an exception if we are already running or have been completed.

2021-03-21 11:22 UTC, jonas-zipprick commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +     * Stays set even after reconnects.
Oh yeah, right

2021-03-21 11:23 UTC, jonas-zipprick commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +            const onclose = this.socket ? this.socket.onclose : null;
I'm using fields now

2021-03-21 11:28 UTC, jonas-zipprick commented on packages/stubs/node/src/ts/messaging/ReconnectingWebSocket.ts
>          this.throwIfNotYetConnected();
Using fields now

2021-03-21 11:31 UTC, jonas-zipprick commented on packages/stubs/browser/src/ts/messaging/ReconnectingWebSocket.ts
> +                resolve(errStatus(`Host unreachable. ${JSON.stringify(ev)}.`));
I moved the status to the close listener and removed the error listener.

2021-03-21 11:41 UTC, jonas-zipprick commented
> i meant lets add a test for the subs

They are already being tested in RpcServer.test.ts

2021-03-21 11:53 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
>  export class WebSocketBidiStreamStub<ClientMessageT, ServerMessageT>
They are already being tested in RpcServer.test.ts

2021-03-21 12:18 UTC, jonas-zipprick commented on packages/rpc/common/src/ts/websocket/WebSocketServerStreamStub.ts
> +        this.complete(getOk());
Ok, removed the line and added a check.

2021-03-21 12:20 UTC, eliasgroll approved these changes

2021-03-21 12:21 UTC, eliasgroll commented on packages/rpc/common/src/ts/websocket/WebSocketBidiStreamStub.ts
>  export class WebSocketBidiStreamStub<ClientMessageT, ServerMessageT>
Could deserver another, but agreed, fine for now.

2021-03-21 12:22 UTC, merged