Add an rpc server load test.
0cfg/0cfg-rpc pull request #24
Opened 2021-12-06 16:56 UTC by jonas-zipprick

Adds a load test to the rpc server

# Def. of Done
- [x] Changes described in changelog.md 📝 
- [x] Automatic tests written 🧪
- [x] Manually tested 🧪
- [x] Good code style
- [x] Necessary migrate instructions added to migrate.md 🚀
- [x] No known issues

2021-12-07 04:37 UTC, romfrolov approved these changes

2021-12-07 04:38 UTC, romfrolov requested changes
The code looks good, but the tests are failing.

2021-12-07 17:13 UTC, romfrolov approved these changes

2022-01-03 00:09 UTC, eliasgroll approved these changes

2022-01-03 00:09 UTC, merged