Fix leading slashes
0cfg/0cfg-rpc pull request #29
Opened 2022-01-26 06:59 UTC by SNSTRUTHERS

Closes https://github.com/0cfg/rpc/issues/28

# Def. of Done
- [X] Changes described in changelog.md 📝 
- [ ] Automatic tests written 🧪
- [X] Manually tested 🧪
- [X] Good code style
- [X] Necessary migrate instructions added to migrate.md 🚀
- [X] No known issues

2022-01-26 09:04 UTC, romfrolov approved these changes

2022-02-24 08:00 UTC, schrodit requested changes

2022-02-24 17:21 UTC, schrodit requested changes

2022-02-24 17:21 UTC, schrodit commented on packages/rpc/node/src/ts/RpcServer.ts
> +            const trimPrefix = (s: string, prefix: string): string => s.replace(`^${prefix}`, '');
guess this will break because `/` is not escaped?

2022-02-25 08:23 UTC, schrodit requested changes

2022-02-25 08:23 UTC, schrodit commented on packages/rpc/node/src/ts/RpcServer.ts
> +                s.replace(`^${prefix.replace(/[.,\/!:{}()\[\]]/g, (x) => '\\' + x)}`, '');
ok this looks overly complex now. Also here it is not really reusable.

So either move the function to the a rpc common package and use something like
```
function  trimPrefix(s:string, prefix: string): string {
    return s.startsWith(prefix) ? s.slice(prefix.length) : s;
}
```
or lets just call the function `trimSlash` and just make it remove the leading slash.

2022-02-25 17:14 UTC, romfrolov approved these changes

2022-02-25 17:34 UTC, schrodit approved these changes

2022-02-26 07:39 UTC, merged